name: Scheduled Data Ingestion

on:
  schedule:
  - cron: "0 */2 * * *"
   # Runs every day at 06:00 UTC
  workflow_dispatch:       # Allows manual run

jobs:
  run-ingestion:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run ingestion script
        run: python ingest_data.py
